### ISSUE TITLE
交易所文档_Coinhouse新手学院

### ISSUE THREAD

**Issue by CoinhouseEX** [CoinhouseEX/coinub-pm#5]
<img width="690" alt="截屏2024-01-04 22 54 33" src="https://github.com/CoinhouseEX/coinub-pm/assets/155474338/6733fd0d-8eca-4790-a5a5-4056560ac263">

**Comment by CoinhouseEX** [comment]
参考：https://www.okx.com/cn/learn

洗稿即可

**Comment by Olivia2077** [comment]
主打交易洼地，学院更多侧重在币圈热点中，刺激用户购买

上币完善后，可在文章中加入链接，直接引导用户去交易界面进行交易

![image](https://github.com/CoinhouseEX/coinub-pm/assets/156086415/f5aa3a07-845c-4a2a-86bb-92b3106a1996)
